# This file was generated by GoReleaser. DO NOT EDIT.
cask "claudectx" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "88cff1057abcdd9864211a98ed2cde7cd33a2beb0518dea6f6de1c2fc0745c93"
      url "https://github.com/RaphaelNeumann/claudectx/releases/download/v#{version}/claudectx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1922e3f89cc6e8e10378c6820ab03dd49c1a4f54f5688ea4675616ec27f46bee"
      url "https://github.com/RaphaelNeumann/claudectx/releases/download/v#{version}/claudectx_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "claudectx"
  desc "Switch between multiple Claude Code accounts"
  homepage "https://github.com/RaphaelNeumann/claudectx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claudectx"

  # No zap stanza required

end
