# This file was generated by GoReleaser. DO NOT EDIT.
cask "claudectx" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "6c77695da59b52dbd4ab203165eaa3721d339474cca7dc5fbe11caf55133e999"
      url "https://github.com/RaphaelNeumann/claudectx/releases/download/v#{version}/claudectx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "18edbce534ce9096ff21bcedf470b673d9724c629462bb5a131e5696e96806f5"
      url "https://github.com/RaphaelNeumann/claudectx/releases/download/v#{version}/claudectx_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "claudectx"
  desc "Switch between multiple Claude Code accounts"
  homepage "https://github.com/RaphaelNeumann/claudectx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claudectx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claudectx"]
    end
  end

  # No zap stanza required

end
