# This file was generated by GoReleaser. DO NOT EDIT.
cask "claudectx" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "d831a5c29288011820ff17dbc53a1776949da8a1baaf24ec2d5a680077020ddc"
      url "https://github.com/RaphaelNeumann/claudectx/releases/download/v#{version}/claudectx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "57b90e06d6353748bd1156f845552417152e3239a6d7934562f50bb35798f137"
      url "https://github.com/RaphaelNeumann/claudectx/releases/download/v#{version}/claudectx_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "claudectx"
  desc "Switch between multiple Claude Code accounts"
  homepage "https://github.com/RaphaelNeumann/claudectx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claudectx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claudectx"]
    end
  end

  # No zap stanza required

end
